// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package p4.v1.p4runtime

@SerialVersionUID(0L)
final case class Action(
    actionId: _root_.scala.Int = 0,
    params: _root_.scala.Seq[p4.v1.p4runtime.Action.Param] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Action] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = actionId
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      params.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = actionId
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      params.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withActionId(__v: _root_.scala.Int): Action = copy(actionId = __v)
    def clearParams = copy(params = _root_.scala.Seq.empty)
    def addParams(__vs: p4.v1.p4runtime.Action.Param *): Action = addAllParams(__vs)
    def addAllParams(__vs: Iterable[p4.v1.p4runtime.Action.Param]): Action = copy(params = params ++ __vs)
    def withParams(__v: _root_.scala.Seq[p4.v1.p4runtime.Action.Param]): Action = copy(params = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = actionId
          if (__t != 0) __t else null
        }
        case 4 => params
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(actionId)
        case 4 => _root_.scalapb.descriptors.PRepeated(params.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: p4.v1.p4runtime.Action.type = p4.v1.p4runtime.Action
    // @@protoc_insertion_point(GeneratedMessage[p4.v1.Action])
}

object Action extends scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.Action] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.Action] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): p4.v1.p4runtime.Action = {
    var __actionId: _root_.scala.Int = 0
    val __params: _root_.scala.collection.immutable.VectorBuilder[p4.v1.p4runtime.Action.Param] = new _root_.scala.collection.immutable.VectorBuilder[p4.v1.p4runtime.Action.Param]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __actionId = _input__.readUInt32()
        case 34 =>
          __params += _root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.Action.Param](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    p4.v1.p4runtime.Action(
        actionId = __actionId,
        params = __params.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[p4.v1.p4runtime.Action] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      p4.v1.p4runtime.Action(
        actionId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        params = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Seq[p4.v1.p4runtime.Action.Param]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P4RuntimeProto.javaDescriptor.getMessageTypes().get(10)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P4RuntimeProto.scalaDescriptor.messages(10)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 4 => __out = p4.v1.p4runtime.Action.Param
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      _root_.p4.v1.p4runtime.Action.Param
    )
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = p4.v1.p4runtime.Action(
    actionId = 0,
    params = _root_.scala.Seq.empty
  )
  @SerialVersionUID(0L)
  final case class Param(
      paramId: _root_.scala.Int = 0,
      value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY,
      unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
      ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Param] {
      @transient
      private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
      private[this] def __computeSerializedSize(): _root_.scala.Int = {
        var __size = 0
        
        {
          val __value = paramId
          if (__value != 0) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(2, __value)
          }
        };
        
        {
          val __value = value
          if (!__value.isEmpty) {
            __size += _root_.com.google.protobuf.CodedOutputStream.computeBytesSize(3, __value)
          }
        };
        __size += unknownFields.serializedSize
        __size
      }
      override def serializedSize: _root_.scala.Int = {
        var __size = __serializedSizeMemoized
        if (__size == 0) {
          __size = __computeSerializedSize() + 1
          __serializedSizeMemoized = __size
        }
        __size - 1
        
      }
      def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
        {
          val __v = paramId
          if (__v != 0) {
            _output__.writeUInt32(2, __v)
          }
        };
        {
          val __v = value
          if (!__v.isEmpty) {
            _output__.writeBytes(3, __v)
          }
        };
        unknownFields.writeTo(_output__)
      }
      def withParamId(__v: _root_.scala.Int): Param = copy(paramId = __v)
      def withValue(__v: _root_.com.google.protobuf.ByteString): Param = copy(value = __v)
      def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
      def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
      def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
        (__fieldNumber: @_root_.scala.unchecked) match {
          case 2 => {
            val __t = paramId
            if (__t != 0) __t else null
          }
          case 3 => {
            val __t = value
            if (__t != _root_.com.google.protobuf.ByteString.EMPTY) __t else null
          }
        }
      }
      def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
        _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
        (__field.number: @_root_.scala.unchecked) match {
          case 2 => _root_.scalapb.descriptors.PInt(paramId)
          case 3 => _root_.scalapb.descriptors.PByteString(value)
        }
      }
      def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
      def companion: p4.v1.p4runtime.Action.Param.type = p4.v1.p4runtime.Action.Param
      // @@protoc_insertion_point(GeneratedMessage[p4.v1.Action.Param])
  }
  
  object Param extends scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.Action.Param] {
    implicit def messageCompanion: scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.Action.Param] = this
    def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): p4.v1.p4runtime.Action.Param = {
      var __paramId: _root_.scala.Int = 0
      var __value: _root_.com.google.protobuf.ByteString = _root_.com.google.protobuf.ByteString.EMPTY
      var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
      var _done__ = false
      while (!_done__) {
        val _tag__ = _input__.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 16 =>
            __paramId = _input__.readUInt32()
          case 26 =>
            __value = _input__.readBytes()
          case tag =>
            if (_unknownFields__ == null) {
              _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
            }
            _unknownFields__.parseField(tag, _input__)
        }
      }
      p4.v1.p4runtime.Action.Param(
          paramId = __paramId,
          value = __value,
          unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
      )
    }
    implicit def messageReads: _root_.scalapb.descriptors.Reads[p4.v1.p4runtime.Action.Param] = _root_.scalapb.descriptors.Reads{
      case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
        _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
        p4.v1.p4runtime.Action.Param(
          paramId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0),
          value = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.com.google.protobuf.ByteString]).getOrElse(_root_.com.google.protobuf.ByteString.EMPTY)
        )
      case _ => throw new RuntimeException("Expected PMessage")
    }
    def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = p4.v1.p4runtime.Action.javaDescriptor.getNestedTypes().get(0)
    def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = p4.v1.p4runtime.Action.scalaDescriptor.nestedMessages(0)
    def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
    lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
    def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
    lazy val defaultInstance = p4.v1.p4runtime.Action.Param(
      paramId = 0,
      value = _root_.com.google.protobuf.ByteString.EMPTY
    )
    implicit class ParamLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.Action.Param]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, p4.v1.p4runtime.Action.Param](_l) {
      def paramId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.paramId)((c_, f_) => c_.copy(paramId = f_))
      def value: _root_.scalapb.lenses.Lens[UpperPB, _root_.com.google.protobuf.ByteString] = field(_.value)((c_, f_) => c_.copy(value = f_))
    }
    final val PARAM_ID_FIELD_NUMBER = 2
    final val VALUE_FIELD_NUMBER = 3
    def of(
      paramId: _root_.scala.Int,
      value: _root_.com.google.protobuf.ByteString
    ): _root_.p4.v1.p4runtime.Action.Param = _root_.p4.v1.p4runtime.Action.Param(
      paramId,
      value
    )
    // @@protoc_insertion_point(GeneratedMessageCompanion[p4.v1.Action.Param])
  }
  
  implicit class ActionLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.Action]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, p4.v1.p4runtime.Action](_l) {
    def actionId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.actionId)((c_, f_) => c_.copy(actionId = f_))
    def params: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[p4.v1.p4runtime.Action.Param]] = field(_.params)((c_, f_) => c_.copy(params = f_))
  }
  final val ACTION_ID_FIELD_NUMBER = 1
  final val PARAMS_FIELD_NUMBER = 4
  def of(
    actionId: _root_.scala.Int,
    params: _root_.scala.Seq[p4.v1.p4runtime.Action.Param]
  ): _root_.p4.v1.p4runtime.Action = _root_.p4.v1.p4runtime.Action(
    actionId,
    params
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[p4.v1.Action])
}
