// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package p4.v1.p4runtime

@SerialVersionUID(0L)
final case class ActionProfileActionSet(
    actionProfileActions: _root_.scala.Seq[p4.v1.p4runtime.ActionProfileAction] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ActionProfileActionSet] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      actionProfileActions.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      actionProfileActions.foreach { __v =>
        val __m = __v
        _output__.writeTag(1, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def clearActionProfileActions = copy(actionProfileActions = _root_.scala.Seq.empty)
    def addActionProfileActions(__vs: p4.v1.p4runtime.ActionProfileAction *): ActionProfileActionSet = addAllActionProfileActions(__vs)
    def addAllActionProfileActions(__vs: Iterable[p4.v1.p4runtime.ActionProfileAction]): ActionProfileActionSet = copy(actionProfileActions = actionProfileActions ++ __vs)
    def withActionProfileActions(__v: _root_.scala.Seq[p4.v1.p4runtime.ActionProfileAction]): ActionProfileActionSet = copy(actionProfileActions = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => actionProfileActions
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PRepeated(actionProfileActions.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: p4.v1.p4runtime.ActionProfileActionSet.type = p4.v1.p4runtime.ActionProfileActionSet
    // @@protoc_insertion_point(GeneratedMessage[p4.v1.ActionProfileActionSet])
}

object ActionProfileActionSet extends scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.ActionProfileActionSet] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.ActionProfileActionSet] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): p4.v1.p4runtime.ActionProfileActionSet = {
    val __actionProfileActions: _root_.scala.collection.immutable.VectorBuilder[p4.v1.p4runtime.ActionProfileAction] = new _root_.scala.collection.immutable.VectorBuilder[p4.v1.p4runtime.ActionProfileAction]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __actionProfileActions += _root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.ActionProfileAction](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    p4.v1.p4runtime.ActionProfileActionSet(
        actionProfileActions = __actionProfileActions.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[p4.v1.p4runtime.ActionProfileActionSet] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      p4.v1.p4runtime.ActionProfileActionSet(
        actionProfileActions = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Seq[p4.v1.p4runtime.ActionProfileAction]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P4RuntimeProto.javaDescriptor.getMessageTypes().get(11)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P4RuntimeProto.scalaDescriptor.messages(11)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 1 => __out = p4.v1.p4runtime.ActionProfileAction
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = p4.v1.p4runtime.ActionProfileActionSet(
    actionProfileActions = _root_.scala.Seq.empty
  )
  implicit class ActionProfileActionSetLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.ActionProfileActionSet]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, p4.v1.p4runtime.ActionProfileActionSet](_l) {
    def actionProfileActions: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[p4.v1.p4runtime.ActionProfileAction]] = field(_.actionProfileActions)((c_, f_) => c_.copy(actionProfileActions = f_))
  }
  final val ACTION_PROFILE_ACTIONS_FIELD_NUMBER = 1
  def of(
    actionProfileActions: _root_.scala.Seq[p4.v1.p4runtime.ActionProfileAction]
  ): _root_.p4.v1.p4runtime.ActionProfileActionSet = _root_.p4.v1.p4runtime.ActionProfileActionSet(
    actionProfileActions
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[p4.v1.ActionProfileActionSet])
}
