// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package p4.v1.p4runtime

/** ------------------------------------------------------------------------------
  */
@SerialVersionUID(0L)
final case class ActionProfileMember(
    actionProfileId: _root_.scala.Int = 0,
    memberId: _root_.scala.Int = 0,
    action: _root_.scala.Option[p4.v1.p4runtime.Action] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[ActionProfileMember] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = actionProfileId
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      
      {
        val __value = memberId
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(2, __value)
        }
      };
      if (action.isDefined) {
        val __value = action.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = actionProfileId
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      {
        val __v = memberId
        if (__v != 0) {
          _output__.writeUInt32(2, __v)
        }
      };
      action.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withActionProfileId(__v: _root_.scala.Int): ActionProfileMember = copy(actionProfileId = __v)
    def withMemberId(__v: _root_.scala.Int): ActionProfileMember = copy(memberId = __v)
    def getAction: p4.v1.p4runtime.Action = action.getOrElse(p4.v1.p4runtime.Action.defaultInstance)
    def clearAction: ActionProfileMember = copy(action = _root_.scala.None)
    def withAction(__v: p4.v1.p4runtime.Action): ActionProfileMember = copy(action = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = actionProfileId
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = memberId
          if (__t != 0) __t else null
        }
        case 3 => action.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(actionProfileId)
        case 2 => _root_.scalapb.descriptors.PInt(memberId)
        case 3 => action.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: p4.v1.p4runtime.ActionProfileMember.type = p4.v1.p4runtime.ActionProfileMember
    // @@protoc_insertion_point(GeneratedMessage[p4.v1.ActionProfileMember])
}

object ActionProfileMember extends scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.ActionProfileMember] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.ActionProfileMember] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): p4.v1.p4runtime.ActionProfileMember = {
    var __actionProfileId: _root_.scala.Int = 0
    var __memberId: _root_.scala.Int = 0
    var __action: _root_.scala.Option[p4.v1.p4runtime.Action] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __actionProfileId = _input__.readUInt32()
        case 16 =>
          __memberId = _input__.readUInt32()
        case 26 =>
          __action = Option(__action.fold(_root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.Action](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    p4.v1.p4runtime.ActionProfileMember(
        actionProfileId = __actionProfileId,
        memberId = __memberId,
        action = __action,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[p4.v1.p4runtime.ActionProfileMember] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      p4.v1.p4runtime.ActionProfileMember(
        actionProfileId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        memberId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        action = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[p4.v1.p4runtime.Action]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P4RuntimeProto.javaDescriptor.getMessageTypes().get(13)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P4RuntimeProto.scalaDescriptor.messages(13)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 3 => __out = p4.v1.p4runtime.Action
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = p4.v1.p4runtime.ActionProfileMember(
    actionProfileId = 0,
    memberId = 0,
    action = _root_.scala.None
  )
  implicit class ActionProfileMemberLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.ActionProfileMember]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, p4.v1.p4runtime.ActionProfileMember](_l) {
    def actionProfileId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.actionProfileId)((c_, f_) => c_.copy(actionProfileId = f_))
    def memberId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.memberId)((c_, f_) => c_.copy(memberId = f_))
    def action: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.Action] = field(_.getAction)((c_, f_) => c_.copy(action = Option(f_)))
    def optionalAction: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[p4.v1.p4runtime.Action]] = field(_.action)((c_, f_) => c_.copy(action = f_))
  }
  final val ACTION_PROFILE_ID_FIELD_NUMBER = 1
  final val MEMBER_ID_FIELD_NUMBER = 2
  final val ACTION_FIELD_NUMBER = 3
  def of(
    actionProfileId: _root_.scala.Int,
    memberId: _root_.scala.Int,
    action: _root_.scala.Option[p4.v1.p4runtime.Action]
  ): _root_.p4.v1.p4runtime.ActionProfileMember = _root_.p4.v1.p4runtime.ActionProfileMember(
    actionProfileId,
    memberId,
    action
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[p4.v1.ActionProfileMember])
}
