// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package p4.v1.p4runtime

/** ------------------------------------------------------------------------------
  * For WriteRequest, Update.Type must be MODIFY.
  * For ReadRequest, the scope is defined as follows:
  * - All meter cells for all meters if meter_id = 0 (default).
  * - All meter cells for given meter_id if index is unset (default).
  */
@SerialVersionUID(0L)
final case class MeterEntry(
    meterId: _root_.scala.Int = 0,
    index: _root_.scala.Option[p4.v1.p4runtime.Index] = _root_.scala.None,
    config: _root_.scala.Option[p4.v1.p4runtime.MeterConfig] = _root_.scala.None,
    counterData: _root_.scala.Option[p4.v1.p4runtime.MeterCounterData] = _root_.scala.None,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MeterEntry] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = meterId
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      if (index.isDefined) {
        val __value = index.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (config.isDefined) {
        val __value = config.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      if (counterData.isDefined) {
        val __value = counterData.get
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = meterId
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      index.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      config.foreach { __v =>
        val __m = __v
        _output__.writeTag(3, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      counterData.foreach { __v =>
        val __m = __v
        _output__.writeTag(4, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withMeterId(__v: _root_.scala.Int): MeterEntry = copy(meterId = __v)
    def getIndex: p4.v1.p4runtime.Index = index.getOrElse(p4.v1.p4runtime.Index.defaultInstance)
    def clearIndex: MeterEntry = copy(index = _root_.scala.None)
    def withIndex(__v: p4.v1.p4runtime.Index): MeterEntry = copy(index = Option(__v))
    def getConfig: p4.v1.p4runtime.MeterConfig = config.getOrElse(p4.v1.p4runtime.MeterConfig.defaultInstance)
    def clearConfig: MeterEntry = copy(config = _root_.scala.None)
    def withConfig(__v: p4.v1.p4runtime.MeterConfig): MeterEntry = copy(config = Option(__v))
    def getCounterData: p4.v1.p4runtime.MeterCounterData = counterData.getOrElse(p4.v1.p4runtime.MeterCounterData.defaultInstance)
    def clearCounterData: MeterEntry = copy(counterData = _root_.scala.None)
    def withCounterData(__v: p4.v1.p4runtime.MeterCounterData): MeterEntry = copy(counterData = Option(__v))
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = meterId
          if (__t != 0) __t else null
        }
        case 2 => index.orNull
        case 3 => config.orNull
        case 4 => counterData.orNull
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(meterId)
        case 2 => index.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 3 => config.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
        case 4 => counterData.map(_.toPMessage).getOrElse(_root_.scalapb.descriptors.PEmpty)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: p4.v1.p4runtime.MeterEntry.type = p4.v1.p4runtime.MeterEntry
    // @@protoc_insertion_point(GeneratedMessage[p4.v1.MeterEntry])
}

object MeterEntry extends scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.MeterEntry] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[p4.v1.p4runtime.MeterEntry] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): p4.v1.p4runtime.MeterEntry = {
    var __meterId: _root_.scala.Int = 0
    var __index: _root_.scala.Option[p4.v1.p4runtime.Index] = _root_.scala.None
    var __config: _root_.scala.Option[p4.v1.p4runtime.MeterConfig] = _root_.scala.None
    var __counterData: _root_.scala.Option[p4.v1.p4runtime.MeterCounterData] = _root_.scala.None
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __meterId = _input__.readUInt32()
        case 18 =>
          __index = Option(__index.fold(_root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.Index](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 26 =>
          __config = Option(__config.fold(_root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.MeterConfig](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case 34 =>
          __counterData = Option(__counterData.fold(_root_.scalapb.LiteParser.readMessage[p4.v1.p4runtime.MeterCounterData](_input__))(_root_.scalapb.LiteParser.readMessage(_input__, _)))
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    p4.v1.p4runtime.MeterEntry(
        meterId = __meterId,
        index = __index,
        config = __config,
        counterData = __counterData,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[p4.v1.p4runtime.MeterEntry] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      p4.v1.p4runtime.MeterEntry(
        meterId = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        index = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).flatMap(_.as[_root_.scala.Option[p4.v1.p4runtime.Index]]),
        config = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).flatMap(_.as[_root_.scala.Option[p4.v1.p4runtime.MeterConfig]]),
        counterData = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).flatMap(_.as[_root_.scala.Option[p4.v1.p4runtime.MeterCounterData]])
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = P4RuntimeProto.javaDescriptor.getMessageTypes().get(16)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = P4RuntimeProto.scalaDescriptor.messages(16)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = p4.v1.p4runtime.Index
      case 3 => __out = p4.v1.p4runtime.MeterConfig
      case 4 => __out = p4.v1.p4runtime.MeterCounterData
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = p4.v1.p4runtime.MeterEntry(
    meterId = 0,
    index = _root_.scala.None,
    config = _root_.scala.None,
    counterData = _root_.scala.None
  )
  implicit class MeterEntryLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.MeterEntry]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, p4.v1.p4runtime.MeterEntry](_l) {
    def meterId: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.meterId)((c_, f_) => c_.copy(meterId = f_))
    def index: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.Index] = field(_.getIndex)((c_, f_) => c_.copy(index = Option(f_)))
    def optionalIndex: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[p4.v1.p4runtime.Index]] = field(_.index)((c_, f_) => c_.copy(index = f_))
    def config: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.MeterConfig] = field(_.getConfig)((c_, f_) => c_.copy(config = Option(f_)))
    def optionalConfig: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[p4.v1.p4runtime.MeterConfig]] = field(_.config)((c_, f_) => c_.copy(config = f_))
    def counterData: _root_.scalapb.lenses.Lens[UpperPB, p4.v1.p4runtime.MeterCounterData] = field(_.getCounterData)((c_, f_) => c_.copy(counterData = Option(f_)))
    def optionalCounterData: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Option[p4.v1.p4runtime.MeterCounterData]] = field(_.counterData)((c_, f_) => c_.copy(counterData = f_))
  }
  final val METER_ID_FIELD_NUMBER = 1
  final val INDEX_FIELD_NUMBER = 2
  final val CONFIG_FIELD_NUMBER = 3
  final val COUNTER_DATA_FIELD_NUMBER = 4
  def of(
    meterId: _root_.scala.Int,
    index: _root_.scala.Option[p4.v1.p4runtime.Index],
    config: _root_.scala.Option[p4.v1.p4runtime.MeterConfig],
    counterData: _root_.scala.Option[p4.v1.p4runtime.MeterCounterData]
  ): _root_.p4.v1.p4runtime.MeterEntry = _root_.p4.v1.p4runtime.MeterEntry(
    meterId,
    index,
    config,
    counterData
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[p4.v1.MeterEntry])
}
